version: "3.8"

services:
  postgres:
    image: postgres:16.1
    environment:
      POSTGRES_DB: users
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend

  redis:
    image: redis:7
    command: [ "redis-server", "--requirepass", "redis", "--bind", "0.0.0.0" ]
    ports:
      - "6379:6379"
    networks:
      - backend

  user-service:
    build: .
    image: user-service
    environment:
      SPRING_PROFILES_ACTIVE: docker
      DB_URL: jdbc:postgresql://postgres:5432/users
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: redis
      JWT_SECRET: xlnHvzm1P50Fh2VUVJwfabMClaOUzPKHvfOeYZQoRSE=
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redis
    networks:
      - backend

volumes:
  postgres_data:

networks:
  backend:
    external: true
