name: CI Pipeline

on:
  push:
    branches:
      - ci

jobs:
  build-test-sonar-docker:
    runs-on: ubuntu-latest


    services:
      redis:
        image: redis:7
        ports:
          - 6379:6379

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build
        run: ./gradlew build -x test

      - name: Run tests
        run: ./gradlew test